#include "solverMaze.h"
#include "ssd1306.h"
#ifdef __cplusplus
    #include <cstdlib>
#else
    #include <stdlib.h>
#endif
positionRobot *pt_zhonx_position;
labyrinthe maze_to_discovert = {{{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,2000},},{{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,2000},},{{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,NO_WALL,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,NO_WALL,WALL_PRESENCE,2000},{WALL_PRESENCE,WALL_PRESENCE,NO_WALL,NO_WALL,2000},},{{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000},{WALL_PRESENCE,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,WALL_PRESENCE,2000},{NO_WALL,NO_WALL,WALL_PRESENCE,NO_WALL,2000},{NO_WALL,WALL_PRESENCE,WALL_PRESENCE,NO_WALL,2000}}}};
void goOrientation(char *orientationZhonx, char directionToGo)
{
	*orientationZhonx= directionToGo;
    return;
}
void doUTurn(positionRobot *positionZhonx)
{
    return;
}
void moveZhonxArc (int direction_to_go, positionRobot *positionZhonx, int numberOfCase, char end_mid_of_case, char chain)
{
	positionZhonx->orientation = direction_to_go;
}
int floorSensorCalibrate(void)
{
    return 1;
}
int waitValidation(unsigned long timeout)
{
    return 1;
}
void newCell(walls new_walls, labyrinthe *maze, positionRobot positionZhonx)
{
    #if DEBUG > 1
	/*print walls position*/
		ssd1306ClearRect(64,0,64,64);
		if (new_walls.front == WALL_PRESENCE)
		{
			ssd1306FillRect(64,49,54,5);
		}
		switch (new_walls.next_front)
		{
			case WALL_PRESENCE:
				ssd1306FillRect(64,0,54,5);
				break;
			case NO_KNOWN :
				ssd1306DrawRect(64,0,54,5);
				break;
			default:
				break;
		}
		switch (new_walls.left)
		{
			case WALL_PRESENCE:
				ssd1306FillRect(64,0,5,54);
				break;
			case NO_KNOWN :
				ssd1306DrawRect(64,0,5,54);
				break;
			default:
				break;
		}
		switch (new_walls.right)
		{
			case WALL_PRESENCE:
				ssd1306FillRect(113,0,5,54);
				break;
			case NO_KNOWN :
				ssd1306DrawRect(113,0,5,54);
				break;
			default:
				break;
		}
		ssd1306Refresh();
		/*end print wall position*/
#endif
//		telemetersStop();
//		motorsSleepDriver(ON);
	switch (positionZhonx.orientation)
	{
		case NORTH :
//				maze->cell[(int)(positionZhonx.x)][(int)(positionZhonx.y-1)].wall_north=new_walls.next_front;
//					maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y- 2)].wall_south = new_walls.next_front;
			if(positionZhonx.midOfCell == false)
			{
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_east = new_walls.right;
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_west = new_walls.left;

				if (positionZhonx.x < (MAZE_SIZE - 1))
					maze->cell[(int) (positionZhonx.x + 1)][(int) (positionZhonx.y)].wall_west = new_walls.right; // TODO : verify the "y-1"
				if (positionZhonx.x > 0)
					maze->cell[(int) (positionZhonx.x - 1)][(int) (positionZhonx.y)].wall_east = new_walls.left;
			}
			if (positionZhonx.y > 0)
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y - 1)].wall_south = new_walls.front;

			maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_north = new_walls.front;
			break;

		case EAST :

				if(positionZhonx.midOfCell == false)
				{
					maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_south = new_walls.right;
					maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_north = new_walls.left;

					if (positionZhonx.y < (MAZE_SIZE - 1))
						maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y + 1)].wall_north = new_walls.right;
					if (positionZhonx.y > 0)
						maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y - 1)].wall_south = new_walls.left;

				}
			if (positionZhonx.x < (MAZE_SIZE - 1) )
				maze->cell[(int) (positionZhonx.x + 1)][(int) (positionZhonx.y)].wall_west = new_walls.front;
			maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_east = new_walls.front;
			break;

		case SOUTH :

			if(positionZhonx.midOfCell == false)
			{
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_west = new_walls.right;
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_east = new_walls.left;

				if (positionZhonx.x > 0)
					maze->cell[(int) (positionZhonx.x - 1)][(int) (positionZhonx.y)].wall_east = new_walls.right;
				if (positionZhonx.x < (MAZE_SIZE - 1))
					maze->cell[(int) (positionZhonx.x + 1)][(int) (positionZhonx.y)].wall_west = new_walls.left;
			}
			if (positionZhonx.y > 0)
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y + 1)].wall_north = new_walls.front;
			maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_south =
					new_walls.front;
			break;

		case WEST :
			if(positionZhonx.midOfCell == false)
			{
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_north = new_walls.right;
				maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_south = new_walls.left;


				if (positionZhonx.y > 0)
					maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y - 1)].wall_south = new_walls.right;
				if (positionZhonx.y < (MAZE_SIZE - 1))
					maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y + 1)].wall_north = new_walls.left;
			}
			if (positionZhonx.x > 0)
				maze->cell[(int) (positionZhonx.x - 1)][(int) (positionZhonx.y)].wall_east = new_walls.front;
			maze->cell[(int) (positionZhonx.x)][(int) (positionZhonx.y)].wall_west = new_walls.front;
			break;
	}
}
walls getCellState (void)
{
    walls returnValue;
	switch (pt_zhonx_position->orientation)
	{
		case NORTH:
			returnValue.front=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_north;
			returnValue.right=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_east;
			returnValue.left=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_west;
			break;
		case EAST:
			returnValue.front=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_east;
			returnValue.right=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_south;
			returnValue.left=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_north;
			break;
		case SOUTH:
			returnValue.front=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_south;
			returnValue.right=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_west;
			returnValue.left=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_east;
			break;
		case WEST:
			returnValue.front=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_west;
			returnValue.right=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_north;
			returnValue.left=maze_to_discovert.cell[pt_zhonx_position->x][pt_zhonx_position->y].wall_south;
			break;
		default:
			break;
	}
    return returnValue;
}
void move_zhonx_arc (int direction_to_go, positionRobot *positionZhonx, int numberOfCell, char end_mid_of_case, char chain)
{
	positionZhonx->midOfCell=end_mid_of_case;
	positionZhonx->orientation = direction_to_go;
    return;
}

void telemetersStop()
{
    return;
}
void telemetersStart()
{
    return;
}
void telemetersInit()
{
    return;
}
void mainControlInit ()
{
    return;
}
void motorsSleepDriver (char is_on)
{
    return;
}
int move(float angle, float radius_or_distance, float max_speed, float end_speed)
{
    return 1;
}
int rotate90WithCal(int rotation_type, float max_speed, float end_speed)
{
    return 1;
}

bool isEndMove()
{
    return true;
}
